name: Build Sphinx HTML

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Sphinx HTML
        run: |
          cd docs
          make html

      - name: Upload HTML Docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/

      - name: Push to GitLab Pages Repo
        run: |
          git clone https://${GL_USERNAME}:${GL_TOKEN}@git.gfz-potsdam.de/spsw/swvo.git repo
          cd repo
          git config user.name "GitHub Actions (by ${GITHUB_ACTOR})"
          git config user.email "actions@github.com"
          rm -rf docs
          cp -r ../docs/_build/html ./docs
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          git add -A docs
          git commit -m "Update docs from GitHub Actions (commit ${SHORT_SHA} by ${GITHUB_ACTOR})" || echo "No changes to commit"
          git push origin main
        env:
          GL_USERNAME: ${{ secrets.GL_USERNAME }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
